object frmFavorites: TfrmFavorites
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  Caption = 'ATS LAB - MEMOIRES FAVORITES'
  ClientHeight = 500
  ClientWidth = 760
  Color = 1184018
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clSilver
  Font.Height = -13
  Font.Name = 'Georgia'
  Font.Style = []
  Position = poScreenCenter
  TextHeight = 15
  object lblTitle: TLabel
    Left = 24
    Top = 18
    Width = 330
    Height = 25
    Caption = 'ATS LAB  -  MEMOIRES FAVORITES'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = 7848653
    Font.Height = -19
    Font.Name = 'Georgia'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object lblHint: TLabel
    Left = 24
    Top = 52
    Width = 537
    Height = 15
    Caption = 'Double-clic pour rappeler une memoire. AJOUTER memorise l''etat radio courant.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = 11579568
    Font.Height = -12
    Font.Name = 'Consolas'
    Font.Style = []
    ParentFont = False
  end
  object lstFavorites: TListBox
    Left = 24
    Top = 82
    Width = 712
    Height = 342
    Color = 1118481
    Font.Charset = DEFAULT_CHARSET
    Font.Color = 11579568
    Font.Height = -14
    Font.Name = 'Consolas'
    Font.Style = []
    ItemHeight = 17
    ParentFont = False
    TabOrder = 0
    OnClick = lstFavoritesClick
    OnDblClick = lstFavoritesDblClick
  end
  object btnAdd: TButton
    Left = 24
    Top = 446
    Width = 112
    Height = 32
    Caption = 'AJOUTER'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Georgia'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 1
    OnClick = btnAddClick
  end
  object btnRename: TButton
    Left = 136
    Top = 446
    Width = 112
    Height = 32
    Caption = 'RENOMMER'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Georgia'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 2
    OnClick = btnRenameClick
  end
  object btnUpdate: TButton
    Left = 248
    Top = 446
    Width = 112
    Height = 32
    Caption = 'ACTUALISER'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Georgia'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 3
    OnClick = btnUpdateClick
  end
  object btnDelete: TButton
    Left = 368
    Top = 446
    Width = 112
    Height = 32
    Caption = 'SUPPRIMER'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Georgia'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 4
    OnClick = btnDeleteClick
  end
  object btnRecall: TButton
    Left = 488
    Top = 446
    Width = 112
    Height = 32
    Caption = 'RAPPELER'
    Default = True
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Georgia'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 5
    OnClick = btnRecallClick
  end
  object btnClose: TButton
    Left = 608
    Top = 446
    Width = 128
    Height = 32
    Cancel = True
    Caption = 'FERMER'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Georgia'
    Font.Style = [fsBold]
    ModalResult = 2
    ParentFont = False
    TabOrder = 6
    OnClick = btnCloseClick
  end
end
